
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator, TransformerMixin

import joblib

from app.message_router.spacy_preprocessor import SpacyPreprocessor

# -------------------------
# Simple spaCy-based preprocessor transformer
# -------------------------

# -------------------------
# Training data (small demo -- expand for production)
# -------------------------
training_data = [
    # Animal Classification (20 examples)
("what animal is in this image?", "animal_classification"),
("identify this creature", "animal_classification"),
("whats this animal?", "animal_classification"),
("who is this??", "animal_classification"),
("tell me the species", "animal_classification"),
("what type of animal is this?", "animal_classification"),
("classify the animal pls", "animal_classification"),
("can you recognize this animal?", "animal_classification"),
("any idea what this is?", "animal_classification"),
("identify animal plz", "animal_classification"),
("whats the creature name?", "animal_classification"),
("tell me what this animal called", "animal_classification"),
("what species is shown?", "animal_classification"),
("plz identify this animal", "animal_classification"),
("this animal is what?", "animal_classification"),
("whats the name of this thing?", "animal_classification"),
("look at this pic, what animal?", "animal_classification"),
("this photo is what animal?", "animal_classification"),
("which mammal is this?", "animal_classification"),
("bird name please?", "animal_classification"),
("what reptile?", "animal_classification"),
("fish type?", "animal_classification"),
("tell me the wildlife name", "animal_classification"),
("identify this bug", "animal_classification"),
("is this a cat or dog?", "animal_classification"),
("what dog breed is this?", "animal_classification"),
("cat breed?", "animal_classification"),
("whats this animal species?", "animal_classification"),
("animal recognition needed", "animal_classification"),
("help me classify this animal", "animal_classification"),
("which species is it?", "animal_classification"),
("who dis animal?", "animal_classification"),
("wt animal?", "animal_classification"),
("animal id pls", "animal_classification"),
("is this an elephant?", "animal_classification"),
("what lion??", "animal_classification"),
("species check pls", "animal_classification"),
("tell me if this is tiger", "animal_classification"),
("is this a bird or bat?", "animal_classification"),
("classify this living thing", "animal_classification"),
("wildlife id pls", "animal_classification"),
("insect id", "animal_classification"),
("species recognition plz", "animal_classification"),
("animal guess?", "animal_classification"),
("whats that creature name", "animal_classification"),
("pls tell me species", "animal_classification"),
("recognize the animal??", "animal_classification"),
("id this pls", "animal_classification"),
("i saw this in jungle, what is it?", "animal_classification"),
("what type of fish is this?", "animal_classification"),
("bird type?", "animal_classification"),
("what reptile species?", "animal_classification"),
("marine animal id pls", "animal_classification"),
("what's this bug called?", "animal_classification"),
("this species is…?", "animal_classification"),
("name this animal now", "animal_classification"),
("any clue what this animal is?", "animal_classification"),
("pls classify", "animal_classification"),
("tell me animal name", "animal_classification"),
("who is this animal?", "animal_classification"),
("id species from image", "animal_classification"),
("species finder pls", "animal_classification"),
("whats this animal dude?", "animal_classification"),
("yo what animal?", "animal_classification"),
("check this animal", "animal_classification"),
("give me name of animal", "animal_classification"),
("animal recognition", "animal_classification"),
("photo id species", "animal_classification"),
("which creature?", "animal_classification"),
("pls id animal", "animal_classification"),
("help recognize animal", "animal_classification"),
("animal name finder", "animal_classification"),
("tell me wildlife species", "animal_classification"),
("classify my animal photo", "animal_classification"),
("is this animal endangered?", "animal_classification"),
("what kind of fish this?", "animal_classification"),
("species id tool", "animal_classification"),
("this is which species?", "animal_classification"),
("pls help identify animal", "animal_classification"),
("animal detection pls", "animal_classification"),
("do u know this animal?", "animal_classification"),
("which wild animal?", "animal_classification"),
("animal label?", "animal_classification"),
("name creature pls", "animal_classification"),
("species plz??", "animal_classification"),
("tell me if its tiger", "animal_classification"),
("cat species??", "animal_classification"),
("dog species??", "animal_classification"),
("who this animal??", "animal_classification"),
("name of this bird?", "animal_classification"),
("is it lion?", "animal_classification"),
("animal in image??", "animal_classification"),
("guess animal pls", "animal_classification"),
("wild animal classify", "animal_classification"),
("can u identify species?", "animal_classification"),
("pls say name", "animal_classification"),
("living being classify", "animal_classification"),
("animal??", "animal_classification"),
("identify??", "animal_classification"),
("whats shown here??", "animal_classification"),
("name animal from pic", "animal_classification"),
("animal classification pls", "animal_classification"),


    # Greeting (15 examples)
("hello", "greeting"),
("helloo", "greeting"),
("hellooo", "greeting"),
("hellooooo", "greeting"),
("helo", "greeting"),
("heloo", "greeting"),
("hellow", "greeting"),
("helloww", "greeting"),
("hellowww", "greeting"),
("hi", "greeting"),
("hii", "greeting"),
("hiii", "greeting"),
("hiiiiii", "greeting"),
("hi there", "greeting"),
("hiya", "greeting"),
("hiyaaa", "greeting"),
("hiiiii friend", "greeting"),
("hey", "greeting"),
("heyy", "greeting"),
("heyyy", "greeting"),
("heyyyyy", "greeting"),
("hey there", "greeting"),
("heyo", "greeting"),
("heyyoo", "greeting"),
("yo", "greeting"),
("yo!", "greeting"),
("yoo", "greeting"),
("yooo", "greeting"),
("yooooo", "greeting"),
("sup", "greeting"),
("sup?", "greeting"),
("sup dude", "greeting"),
("suuup", "greeting"),
("suuuuup", "greeting"),
("wassup", "greeting"),
("wassup?", "greeting"),
("wassuppp", "greeting"),
("wazzup", "greeting"),
("wazzzup", "greeting"),
("whats up", "greeting"),
("whatsupp", "greeting"),
("whatssup", "greeting"),
("what's up bro", "greeting"),
("hey buddy", "greeting"),
("hey bro", "greeting"),
("hey man", "greeting"),
("hey mate", "greeting"),
("hey dude", "greeting"),
("hey friend", "greeting"),
("hey pal", "greeting"),
("heyy buddy!!", "greeting"),
("greetings", "greeting"),
("greetings friend", "greeting"),
("greetings human", "greeting"),
("good morning", "greeting"),
("good morninggg", "greeting"),
("gm", "greeting"),
("goood morning", "greeting"),
("morning!", "greeting"),
("mornin", "greeting"),
("gud morning", "greeting"),
("good afternoon", "greeting"),
("afternoon", "greeting"),
("good eve", "greeting"),
("good evening", "greeting"),
("evening!", "greeting"),
("eveee", "greeting"),
("gd eve", "greeting"),
("good night (as greeting)", "greeting"),
("nighty!", "greeting"),
("nightoo", "greeting"),
("hiya pal", "greeting"),
("hiya dude", "greeting"),
("hi friend", "greeting"),
("hello friend", "greeting"),
("heyy friend", "greeting"),
("nice to meet you", "greeting"),
("pleasure to meet you", "greeting"),
("glad to meet ya", "greeting"),
("yo man", "greeting"),
("yo bro", "greeting"),
("yo dude", "greeting"),
("hey fam", "greeting"),
("hey fammm", "greeting"),
("sup fam", "greeting"),
("hi fam", "greeting"),
("yo fam", "greeting"),
("howdy", "greeting"),
("howdy partner", "greeting"),
("howdy friend", "greeting"),
("aloha", "greeting"),
("ahoy", "greeting"),
("bonjour", "greeting"),
("hola", "greeting"),
("holla", "greeting"),
("ciao", "greeting"),
("salut", "greeting"),
("namaste", "greeting"),
("vanakkam", "greeting"),
("ayubowan", "greeting"),
("yo yo yo", "greeting"),
("yohoo", "greeting"),
("hiiiiiiiiii", "greeting"),
("👋", "greeting"),
("👋 hello", "greeting"),
("✌️ hey", "greeting"),
("🙌 hi", "greeting"),
("😊 hello", "greeting"),
("😃 hey there", "greeting"),
("🥳 yooo", "greeting"),
("🤙 sup", "greeting"),
("🙋 hi", "greeting"),
("🙋‍♂️ hey", "greeting"),
("🙋‍♀️ hello", "greeting"),
("helloo??", "greeting"),
("heyyy??", "greeting"),
("anyone there?", "greeting"),
("knock knock", "greeting"),
("yoo anyone?", "greeting"),
("hi??", "greeting"),
("hey??", "greeting"),
("sup??", "greeting"),


    # Help (15 examples)
("help", "help"),
("help pls", "help"),
("help plz", "help"),
("help me", "help"),
("help me plsss", "help"),
("help me plzz", "help"),
("hellppp", "help"),
("helllp", "help"),
("heeeelp", "help"),
("h e l p", "help"),
("hlp", "help"),
("i need help", "help"),
("i need some help", "help"),
("i need a bit of help", "help"),
("need help", "help"),
("need ur help", "help"),
("need ur assistance", "help"),
("can u help me?", "help"),
("could you help me?", "help"),
("can u pls help?", "help"),
("help me please", "help"),
("help me out", "help"),
("help out pls", "help"),
("please help", "help"),
("plz help me", "help"),
("plsss help", "help"),
("plz assist", "help"),
("assistance pls", "help"),
("i need assistance", "help"),
("assist me", "help"),
("can u assist me?", "help"),
("could u assist?", "help"),
("assist pls", "help"),
("give me some help", "help"),
("i need ur help", "help"),
("i need ur support", "help"),
("support pls", "help"),
("can u support me?", "help"),
("help me with this", "help"),
("plz help me with this", "help"),
("how do i do this?", "help"),
("can u explain this?", "help"),
("explain pls", "help"),
("show me how", "help"),
("how does this work?", "help"),
("idk what to do", "help"),
("don’t know what to do", "help"),
("stuck here", "help"),
("im stuck", "help"),
("im lost", "help"),
("lost here", "help"),
("need guidance", "help"),
("give me guidance", "help"),
("guide me", "help"),
("can you guide me?", "help"),
("need your guidance", "help"),
("help needed", "help"),
("desperate for help", "help"),
("i'm confused", "help"),
("confused here", "help"),
("don’t understand", "help"),
("idk help", "help"),
("what do i do?", "help"),
("what should i do?", "help"),
("what now?", "help"),
("what next?", "help"),
("explain your capabilities", "help"),
("what can you do?", "help"),
("what r u able to do?", "help"),
("what can u help me with?", "help"),
("tell me what u can do", "help"),
("how can you help me?", "help"),
("what support do you offer?", "help"),
("what help can u provide?", "help"),
("what can u help me with?", "help"),
("explain ur features", "help"),
("ur features pls", "help"),
("i need ur features", "help"),
("help center?", "help"),
("tech support pls", "help"),
("customer support", "help"),
("is anyone there to help?", "help"),
("anyone can help?", "help"),
("can i get help?", "help"),
("can u pls explain?", "help"),
("pls explain", "help"),
("need explain", "help"),
("clarify this pls", "help"),
("clarify me", "help"),
("need clarification", "help"),
("im having trouble", "help"),
("having issues", "help"),
("having probs", "help"),
("problem here", "help"),
("got a problem", "help"),
("trouble here", "help"),
("im struggling", "help"),
("struggling pls", "help"),
("need to know how this works", "help"),
("can you show me?", "help"),
("help me figure this out", "help"),
("figure out pls", "help"),
("show me pls", "help"),
("walk me thru this", "help"),
("step me through this", "help"),
("pls guide", "help"),
("teach me", "help"),
("teach me pls", "help"),
("train me", "help"),
("show tutorial", "help"),
("tutorial pls", "help"),
("help desk?", "help"),
("hey i need help", "help"),
("yo can u help", "help"),
("bro help", "help"),
("buddy help me", "help"),
("pls assist me asap", "help"),
("urgent help pls", "help"),
("plzz urgent", "help"),
("SOS", "help"),
("send help", "help"),
("help me asap", "help"),
("emergency help pls", "help"),
("assist asap", "help"),
("i need u", "help"),
("i need ur hand here", "help"),
("can u lend me a hand?", "help"),
("need ur hand", "help"),
("lil help pls", "help"),
("small help pls", "help"),
("quick help pls", "help"),
("fast help pls", "help"),
("need a hand", "help"),
("give me a hand", "help"),
("lend a hand", "help"),


    # Migration Analysis (20 examples)
("analyze the migration data", "migration_analyze"),
("analyze migration dataset", "migration_analyze"),
("analyze this migration file", "migration_analyze"),
("pls analyze migration data", "migration_analyze"),
("can you analyze migration?", "migration_analyze"),
("check migration patterns", "migration_analyze"),
("show me migration patterns", "migration_analyze"),
("migration patterns pls", "migration_analyze"),
("study migration routes", "migration_analyze"),
("migration route study pls", "migration_analyze"),
("examine migration dataset", "migration_analyze"),
("examine migration patterns", "migration_analyze"),
("migration pattern check", "migration_analyze"),
("migration analysis", "migration_analyze"),
("show migration analysis", "migration_analyze"),
("migration analysis pls", "migration_analyze"),
("analyze animal movement data", "migration_analyze"),
("study animal movement", "migration_analyze"),
("analyze animal tracking data", "migration_analyze"),
("check animal tracking", "migration_analyze"),
("process migration dataset", "migration_analyze"),
("process migration tracking info", "migration_analyze"),
("process animal tracking data", "migration_analyze"),
("migration tracking", "migration_analyze"),
("migration analysis needed", "migration_analyze"),
("migration info analysis", "migration_analyze"),
("check migration trends", "migration_analyze"),
("what are the migration trends?", "migration_analyze"),
("migration trend study", "migration_analyze"),
("analyze seasonal migration", "migration_analyze"),
("study seasonal migration", "migration_analyze"),
("examine seasonal movement", "migration_analyze"),
("check migration results", "migration_analyze"),
("show migration results", "migration_analyze"),
("migration results pls", "migration_analyze"),
("give me migration analysis", "migration_analyze"),
("pls show migration study", "migration_analyze"),
("look into migration data", "migration_analyze"),
("can you check migration data?", "migration_analyze"),
("run migration analysis", "migration_analyze"),
("do migration analysis", "migration_analyze"),
("migration data check", "migration_analyze"),
("check migration file", "migration_analyze"),
("analyze this dataset", "migration_analyze"),
("analyze my migration data", "migration_analyze"),
("migration dataset pls", "migration_analyze"),
("look at migration dataset", "migration_analyze"),
("animal migration analysis", "migration_analyze"),
("wildlife migration analysis", "migration_analyze"),
("bird migration analysis", "migration_analyze"),
("study bird migration", "migration_analyze"),
("analyze bird migration data", "migration_analyze"),
("bird migration patterns", "migration_analyze"),
("bird movement study", "migration_analyze"),
("track migration patterns", "migration_analyze"),
("track migration pls", "migration_analyze"),
("migration tracking results", "migration_analyze"),
("migration stats", "migration_analyze"),
("migration statistics", "migration_analyze"),
("show migration statistics", "migration_analyze"),
("analyze migration statistics", "migration_analyze"),
("migration chart pls", "migration_analyze"),
("draw migration map", "migration_analyze"),
("show migration map", "migration_analyze"),
("migration heatmap pls", "migration_analyze"),
("create migration chart", "migration_analyze"),
("migration visualization pls", "migration_analyze"),
("visualize migration", "migration_analyze"),
("plot migration data", "migration_analyze"),
("graph migration dataset", "migration_analyze"),
("migration diagram pls", "migration_analyze"),
("migration routes map", "migration_analyze"),
("map the migration", "migration_analyze"),
("migration flow chart", "migration_analyze"),
("animal movement graph", "migration_analyze"),
("movement data analysis", "migration_analyze"),
("check wildlife movement", "migration_analyze"),
("study wildlife movement patterns", "migration_analyze"),
("examine migration route data", "migration_analyze"),
("migration route info pls", "migration_analyze"),
("migration routes analysis", "migration_analyze"),
("population migration analysis", "migration_analyze"),
("analyze population movement", "migration_analyze"),
("population migration patterns", "migration_analyze"),
("study population migration", "migration_analyze"),
("migration info", "migration_analyze"),
("migration insights pls", "migration_analyze"),
("give me migration insights", "migration_analyze"),
("generate migration report", "migration_analyze"),
("make migration report", "migration_analyze"),
("migration report pls", "migration_analyze"),
("migration details pls", "migration_analyze"),
("get migration details", "migration_analyze"),
("show me movement insights", "migration_analyze"),
("check travel patterns", "migration_analyze"),
("analyze travel routes", "migration_analyze"),
("study movement data", "migration_analyze"),
("movement analysis pls", "migration_analyze"),
("wildlife tracking analysis", "migration_analyze"),
("migration tracking analysis", "migration_analyze"),
("animal path analysis", "migration_analyze"),
("study animal paths", "migration_analyze"),
("study herd movement", "migration_analyze"),
("track seasonal migration", "migration_analyze"),
("migration timeline analysis", "migration_analyze"),
("temporal migration analysis", "migration_analyze"),
("spatial migration analysis", "migration_analyze"),
("geo migration analysis", "migration_analyze"),
("migration dataset study", "migration_analyze"),
("migration big data analysis", "migration_analyze"),


    # Threat Analysis (20 examples)
("what is the endangered level of pandas?", "threat_analyze"),
("tell me the conservation status", "threat_analyze"),
("conservation status pls", "threat_analyze"),
("what's the extinction risk?", "threat_analyze"),
("extinction risk pls", "threat_analyze"),
("how endangered is this species?", "threat_analyze"),
("is this species endangered?", "threat_analyze"),
("is this animal endangered?", "threat_analyze"),
("endangered check pls", "threat_analyze"),
("endangered status?", "threat_analyze"),
("what's the IUCN status?", "threat_analyze"),
("iucn status pls", "threat_analyze"),
("tell me the IUCN category", "threat_analyze"),
("which red list category?", "threat_analyze"),
("red list status?", "threat_analyze"),
("redlist check pls", "threat_analyze"),
("what's the risk status?", "threat_analyze"),
("risk level pls", "threat_analyze"),
("species risk level?", "threat_analyze"),
("how threatened is this animal?", "threat_analyze"),
("is it vulnerable?", "threat_analyze"),
("is it critically endangered?", "threat_analyze"),
("critically endangered or not?", "threat_analyze"),
("what's its protection status?", "threat_analyze"),
("protection status pls", "threat_analyze"),
("what's its safety status?", "threat_analyze"),
("analyze the threat level", "threat_analyze"),
("species threat analysis", "threat_analyze"),
("analyze species threat level", "threat_analyze"),
("conservation threat level?", "threat_analyze"),
("conservation threat check", "threat_analyze"),
("how at risk is this species?", "threat_analyze"),
("is it safe or endangered?", "threat_analyze"),
("safe status?", "threat_analyze"),
("at risk status?", "threat_analyze"),
("threat level pls", "threat_analyze"),
("check threat level", "threat_analyze"),
("what is the threat level for tigers?", "threat_analyze"),
("what's the conservation status of elephants?", "threat_analyze"),
("is this animal protected?", "threat_analyze"),
("protected species?", "threat_analyze"),
("protection category?", "threat_analyze"),
("species vulnerability?", "threat_analyze"),
("how vulnerable is this species?", "threat_analyze"),
("species vulnerability check", "threat_analyze"),
("endangered category?", "threat_analyze"),
("what's the endangered classification?", "threat_analyze"),
("classification status pls", "threat_analyze"),
("is it near threatened?", "threat_analyze"),
("is it least concern?", "threat_analyze"),
("least concern or not?", "threat_analyze"),
("is it vulnerable or endangered?", "threat_analyze"),
("species status info", "threat_analyze"),
("species conservation info", "threat_analyze"),
("species threat info pls", "threat_analyze"),
("is this an endangered animal?", "threat_analyze"),
("are they endangered?", "threat_analyze"),
("endangered??", "threat_analyze"),
("is this species in danger?", "threat_analyze"),
("danger status?", "threat_analyze"),
("is it facing extinction?", "threat_analyze"),
("extinction check pls", "threat_analyze"),
("extinction risk analysis", "threat_analyze"),
("is it going extinct?", "threat_analyze"),
("going extinct or not?", "threat_analyze"),
("population threat?", "threat_analyze"),
("analyze population threat level", "threat_analyze"),
("population decline?", "threat_analyze"),
("population drop status", "threat_analyze"),
("species decline analysis", "threat_analyze"),
("is this population decreasing?", "threat_analyze"),
("species collapse risk?", "threat_analyze"),
("does this species need protection?", "threat_analyze"),
("needs protection?", "threat_analyze"),
("level of protection needed?", "threat_analyze"),
("protection needed or not?", "threat_analyze"),
("should this species be protected?", "threat_analyze"),
("tell me endangered level", "threat_analyze"),
("endangered lvl pls", "threat_analyze"),
("threat lvl pls", "threat_analyze"),
("danger lvl pls", "threat_analyze"),
("is this animal in trouble?", "threat_analyze"),
("species in trouble?", "threat_analyze"),
("trouble status?", "threat_analyze"),
("is it endangered like panda?", "threat_analyze"),
("compare threat level", "threat_analyze"),
("compare endangered status", "threat_analyze"),
("which category is this animal?", "threat_analyze"),
("which category red list?", "threat_analyze"),
("red list endangered?", "threat_analyze"),
("is it in redlist?", "threat_analyze"),
("is it listed endangered?", "threat_analyze"),
("status endangered or not?", "threat_analyze"),
("species conservation threat", "threat_analyze"),
("conservation status analysis", "threat_analyze"),
("analyze extinction risk for this species", "threat_analyze"),
("extinction possibility?", "threat_analyze"),
("probability of extinction?", "threat_analyze"),
("is this rare?", "threat_analyze"),
("rare animal?", "threat_analyze"),
("rareness status?", "threat_analyze"),
("scarcity level?", "threat_analyze"),
("species survival chance?", "threat_analyze"),
("survival risk?", "threat_analyze"),
("will it survive?", "threat_analyze"),
("how safe is it?", "threat_analyze"),
("is it safe?", "threat_analyze"),
("species safety status?", "threat_analyze"),
("future threat?", "threat_analyze"),
("future extinction risk?", "threat_analyze"),


    # Goodbye (15 examples)
("bye", "goodbye"),
("bye!", "goodbye"),
("byee", "goodbye"),
("byeee", "goodbye"),
("goodbye", "goodbye"),
("goodbye!", "goodbye"),
("good bye", "goodbye"),
("see you", "goodbye"),
("see you!", "goodbye"),
("see ya", "goodbye"),
("see ya!", "goodbye"),
("see yaa", "goodbye"),
("cya", "goodbye"),
("cya!", "goodbye"),
("cyaa", "goodbye"),
("cy@!", "goodbye"),
("laters", "goodbye"),
("later", "goodbye"),
("later!", "goodbye"),
("laterz", "goodbye"),
("l8r", "goodbye"),
("l8ter", "goodbye"),
("catch you later", "goodbye"),
("catch ya later", "goodbye"),
("catcha later", "goodbye"),
("talk later", "goodbye"),
("talk to you later", "goodbye"),
("ttyl", "goodbye"),
("ttys", "goodbye"),
("t2yl", "goodbye"),
("take care", "goodbye"),
("take care!", "goodbye"),
("take caree", "goodbye"),
("tc", "goodbye"),
("peace", "goodbye"),
("peace!", "goodbye"),
("peace out", "goodbye"),
("peaceee", "goodbye"),
("peace ✌️", "goodbye"),
("✌️", "goodbye"),
("cheers", "goodbye"),
("cheers!", "goodbye"),
("cheers mate", "goodbye"),
("adios", "goodbye"),
("adiós", "goodbye"),
("adioz", "goodbye"),
("sayonara", "goodbye"),
("sayonaraa", "goodbye"),
("ciao", "goodbye"),
("ciaoo", "goodbye"),
("chao", "goodbye"),
("shalom", "goodbye"),
("au revoir", "goodbye"),
("au revoir!", "goodbye"),
("hasta la vista", "goodbye"),
("hasta luego", "goodbye"),
("gn", "goodbye"),
("gn!", "goodbye"),
("gnite", "goodbye"),
("good night", "goodbye"),
("goodnight", "goodbye"),
("night", "goodbye"),
("nite", "goodbye"),
("ok bye", "goodbye"),
("ok bye!", "goodbye"),
("okayy byee", "goodbye"),
("alright bye", "goodbye"),
("bye for now", "goodbye"),
("bye bye", "goodbye"),
("byebye", "goodbye"),
("bye-bye", "goodbye"),
("bye now", "goodbye"),
("see you soon", "goodbye"),
("see u soon", "goodbye"),
("c u soon", "goodbye"),
("talk soon", "goodbye"),
("talk u soon", "goodbye"),
("brb bye", "goodbye"),
("g2g bye", "goodbye"),
("gtg bye", "goodbye"),
("gotta go bye", "goodbye"),
("g2g", "goodbye"),
("gtg", "goodbye"),
("im out", "goodbye"),
("im out!", "goodbye"),
("im outta here", "goodbye"),
("outtahere", "goodbye"),
("logging off", "goodbye"),
("loggin off", "goodbye"),
("signing off", "goodbye"),
("disconnecting", "goodbye"),
("disconnecting now", "goodbye"),
("end chat", "goodbye"),
("end conv", "goodbye"),
("done chatting", "goodbye"),
("done for now", "goodbye"),
("closing now", "goodbye"),
("close chat", "goodbye"),
("finish chat", "goodbye"),
("exit", "goodbye"),
("exit now", "goodbye"),
("leaving", "goodbye"),
("leaving now", "goodbye"),
("i gotta bounce", "goodbye"),
("gotta bounce", "goodbye"),
("bounce", "goodbye"),
("bouncee", "goodbye"),
("farewell", "goodbye"),
("farewell!", "goodbye"),
("farewell friend", "goodbye"),
("until next time", "goodbye"),
("until later", "goodbye"),
("until we meet again", "goodbye"),
("over and out", "goodbye"),
("roger out", "goodbye"),
("roger bye", "goodbye"),
("signing out", "goodbye"),
("shutting down", "goodbye"),
("done bye", "goodbye"),
("conversation over", "goodbye"),
("chat over", "goodbye"),
("buh bye", "goodbye"),
("buhbye", "goodbye"),
("bbye", "goodbye"),
("bb", "goodbye"),
("bb!", "goodbye"),
("kay bye", "goodbye"),
("kk bye", "goodbye"),
("k bye", "goodbye"),
("kthxbye", "goodbye"),
("k thanks bye", "goodbye"),
("ok thx bye", "goodbye"),
("ok thank you bye", "goodbye"),
("ok im going", "goodbye"),
("im leaving", "goodbye"),
("see u", "goodbye"),
("c u", "goodbye"),
("CU", "goodbye"),
("CU!", "goodbye"),
("laterrrr", "goodbye"),
("byeeeeee", "goodbye"),
("gnnnn", "goodbye"),
("niteee", "goodbye"),
("going offline", "goodbye"),
("offline now", "goodbye"),
("I’m signing out", "goodbye"),
("that’s all, bye", "goodbye"),
("okie bye", "goodbye"),
("okies bye", "goodbye"),
("okii bye", "goodbye"),

]
def nlp_training():
    texts, labels = zip(*training_data)
    preprocessor = SpacyPreprocessor(model="en_core_web_md")

    pipeline = Pipeline([
        ("preprocess", preprocessor),
        ("tfidf", TfidfVectorizer(ngram_range=(1,2), max_features=2000)),
        ("clf", LogisticRegression(max_iter=1000))
    ])

    # Train
    pipeline.fit(texts, labels)
    joblib.dump(pipeline, "app/message_router/chatbot_nlp.plk")

    return pipeline
